version: '3.8'

services:
  
  web:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: project_planning_tool_react
    ports:
      - "3000:3000"
    networks:
      - project-planning-tool-react-network

networks:
  project-planning-tool-react-network:
    driver: bridge
